GET http://localhost:3001/api/notes



###
POST http://localhost:3001/api/notes
Content-Type: application/json
{
  "content"="apprentissage de mongobd",
  "important"=true,
}

{
  "title": "New Note",
  "content": "This is a new note."
}   